# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
    # Schedule updates (each hour)
    schedule: [{ cron: '0 * * * *' }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['public'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  # Your GitHub token
                  token: ${{ secrets.METRICS_TOKEN }}

                  # Options
                  user: jamesinaxx
                  template: markdown
                  filename: README.md
                  markdown: TEMPLATE.md
                  markdown_cache: .cache
                  config_output: markdown
                  base: header, activity, community, repositories, metadata
                  config_timezone: Australia/Sydney
                  plugin_introduction: yes
                  plugin_introduction_title: yes
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: year
                  plugin_music: yes
                  plugin_music_provider: spotify
                  plugin_music_mode: recent
                  plugin_music_limit: 5
                  plugin_music_played_at: yes
                  plugin_music_token: '${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}'
                  plugin_languages: yes
                  plugin_languages_colors: github
                  plugin_languages_details: bytes-size, percentage
                  plugin_languages_threshold: 0%
                  plugin_lines: yes
